depends_on:
    - check-starting

steps:
    sourceforge_deploy:
        image: codeberg.org/jakobdev/python-ci-build-container:latest
        commands:
            - init-container
            - source set-file-env VERSION jdReplace/version.txt
            - full-python-build --name jdReplace --version $VERSION
            - write-changelog-readme --name jdReplace --version $VERSION --output-file Output/README.md
            - sourceforge-upload --upload-dir ./Output/ --project jdreplace --version $VERSION --app-name jdReplace --codeberg-release
        environment:
            SOURCEFORGE_USERNAME:
                from_secret: SOURCEFORGE_USERNAME
            SOURCEFORGE_PASSWORD:
                from_secret: SOURCEFORGE_PASSWORD
            SOURCEFORGE_API_KEY:
                from_secret: SOURCEFORGE_API_KEY
            CODEBERG_API_TOKEN:
                from_secret: CODEBERG_API_TOKEN

when:
    event: tag
