name: jdreplace
version: "2.2"
summary: jdReplace
description: |
  With jdReplace you can replace a text in all files of a directory
base: core18
confinement: strict
grade: stable

parts:
  locales-launch:

  jdreplace:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtopengl
      - python3-setuptools
      - python3-pip
    stage-packages:
      - python3
      - python3-pyqt5
      - python3-pyqt5.qtopengl

apps:
  jdreplace:
    command: locales-launch desktop-launch $SNAP/bin/jdReplace
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - opengl
      - removable-media
      - wayland
      - x11
